import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { convexTestProviderPlugin } from "convex-test-provider/vitest-plugin";

export default defineConfig({
  plugins: [react(), tailwindcss(), convexTestProviderPlugin()],
  test: {
    coverage: {
      enabled: true,
      provider: "v8",
      include: ["src/**/*.{ts,tsx}", "convex/**/*.{ts,tsx}"],
      exclude: [
        // Auto-generated by Convex CLI — never edit manually
        "convex/_generated/**",
        // Test infrastructure — not application code
        "**/*.test.{ts,tsx}",
        "**/*.spec.{ts,tsx}",
        "**/test.setup.ts",
        "**/__tests__/**",
        // Pure wiring files — no testable logic.
        // Do NOT add business logic to these files as they are excluded
        // from coverage and won't be caught by tests.
        "src/main.tsx", // Creates ConvexReactClient, wraps App in providers, renders to DOM
        "src/vite-env.d.ts", // Vite client type declarations, no runtime code
        "convex/auth.ts", // Calls convexAuth({ providers: [Password] }) — config only
        "convex/auth.config.ts", // Provider domain/applicationID config object
        "convex/http.ts", // Creates httpRouter, registers auth HTTP routes — no custom endpoints
      ],
    },
    projects: [
      {
        extends: true,
        test: {
          name: "convex",
          environment: "edge-runtime",
          include: ["convex/**/*.test.{ts,tsx}"],
          server: { deps: { inline: ["convex-test"] } },
          setupFiles: ["convex/test.setup.ts"],
        },
      },
      {
        extends: true,
        resolve: {
          // file:-linked convex-test-provider is symlinked, so its deps resolve
          // from its own node_modules. dedupe forces a single copy of shared libs;
          // server.deps.inline processes the package through Vite's pipeline.
          dedupe: ["react", "react-dom", "convex"],
        },
        test: {
          name: "react",
          environment: "jsdom",
          include: ["src/**/*.test.{ts,tsx}"],
          setupFiles: ["src/test.setup.ts"],
          server: { deps: { inline: ["convex-test-provider"] } },
        },
      },
    ],
  },
});
